plugins { id 'com.android.application' }
android {
    namespace 'com.kostin.app'
    compileSdk 35
    defaultConfig {
        applicationId 'com.kostin.app'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}